### ISSUE TITLE
Module does not appear in the module list

### ISSUE THREAD

**Issue by Ektachrome** [DPDBeNeLux/DPD-Shipping-for-Prestashop-1.6#9]
When installing the latest version of the module for Prestashop 1.6, the module does not appear in the module list after it is successfully uploaded/installed. This is the case when uploading it through the installer in the backoffice or copying it manually to the modules folder through FTP.

Tested versions: 1.6.1.2 / 1.6.1.23

**Comment by dpdplugin** [comment]
I suggest taking the following steps:

- Uninstall the module from the website by removing its folder in ‘modules’.
- Re-download the latest plugin .zip file.
- Extract the .zip file and rename the resulting folder to ‘dpdbenelux’.
- Repack the folder into a new .zip archive, call this archive ‘dpdbenelux’ as well.
- Now try installing the module using this new archive.

**Comment by Ektachrome** [comment]
This worked. Thank you very much!
